[package]
name = "sd3norm"
version = "0.5.2"
authors = ["Mike C. <mwc10>"]

[dependencies]
structopt = "0.2.10"
calamine = "0.14.1"
failure = "0.1.1"
serde = "1.0"
serde_derive = "1.0"
csv = "1.0"
flexi_logger = "0.8"
log = "0.4"
walkdir = "2.1.4"